version: '3.2'

services:
  db:
    image: postgres:14-alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./db/:/var/lib/postgres/data
    restart: always
  logger_server:
    image: python:3.10-alpine



