"""Added content to log table

Revision ID: 0ebd4faeeea9
Revises: 54e57cf3a557
Create Date: 2022-12-31 15:06:38.916353

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0ebd4faeeea9'
down_revision = '54e57cf3a557'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('level', 'numeric_value',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.add_column('log', sa.Column('content', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.alter_column('log', 'level_id',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.drop_constraint('fk__log__level_id__level', 'log', type_='foreignkey')
    op.drop_constraint('fk__log__source_id__source', 'log', type_='foreignkey')
    op.create_foreign_key(op.f('fk__log__source_id__source'), 'log', 'source', ['source_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(op.f('fk__log__level_id__level'), 'log', 'level', ['level_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk__log__level_id__level'), 'log', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk__log__source_id__source'), 'log', schema='public', type_='foreignkey')
    op.create_foreign_key('fk__log__source_id__source', 'log', 'source', ['source_id'], ['id'])
    op.create_foreign_key('fk__log__level_id__level', 'log', 'level', ['level_id'], ['id'])
    op.alter_column('log', 'level_id',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.drop_column('log', 'content')
    op.alter_column('level', 'numeric_value',
               existing_type=sa.SMALLINT(),
               nullable=False)
    # ### end Alembic commands ###
