"""Initial commit

Revision ID: 54e57cf3a557
Revises: 
Create Date: 2022-12-28 17:33:20.344420

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '54e57cf3a557'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    level_model = op.create_table('level',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('numeric_value', sa.SMALLINT(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__level')),
    sa.UniqueConstraint('name', name=op.f('uq__level__name')),
    sa.UniqueConstraint('numeric_value', name=op.f('uq__level__numeric_value')),
    schema='public'
    )
    op.create_table('source',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('token', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__source')),
    sa.UniqueConstraint('name', name=op.f('uq__source__name')),
    schema='public'
    )
    op.create_table('log',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('source_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('level_id', sa.SMALLINT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['public.level.id'], name=op.f('fk__log__level_id__level')),
    sa.ForeignKeyConstraint(['source_id'], ['public.source.id'], name=op.f('fk__log__source_id__source')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__log')),
    schema='public'
    )

    op.bulk_insert(level_model,
                   [
                       {'id': 1, 'name': 'debug', 'numeric_value': 10},
                       {'id': 2, 'name': 'info', 'numeric_value': 20},
                       {'id': 3, 'name': 'warning', 'numeric_value': 30},
                       {'id': 4, 'name': 'error', 'numeric_value': 40},
                       {'id': 5, 'name': 'critical', 'numeric_value': 50},
                       {'id': 6, 'name': 'notset', 'numeric_value': 0},
                   ]
                   )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log', schema='public')
    op.drop_table('source', schema='public')
    op.drop_table('level', schema='public')
    # ### end Alembic commands ###
